name: docker-tag
description: Generate image tags
  
inputs:
  environment:
    description: New tags
    required: true
  version:
    description: Version
    required: true   

outputs:
  tags:
    description: Tags

runs:
  using: 'node20'
  main: 'index.js'
