name: docker-tag
description: Generate image tags
  
inputs:
  environment:
    description: New tags
    required: true
  version:
    description: Version
    required: true   

outputs:
  tags:
    description: Tags
    value: ${{ steps.set-tags.outputs.tags }}

runs:
  using: composite
  steps:
    -
      name: Set tags
      id: set-tags
      shell: bash
      run: |
        tags=()
        tags+=(${{ vars.DEV_AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.DEV_AWS_REGION }}.amazonaws.com/${{ vars.AWS_REPOSITORY }}:${{ inputs.version }}_b${{ github.run_id }}")
        
        tags=$(jq -c -n '$ARGS.positional' --args "${tags[@]}")
        echo "tags=$tags" >> $GITHUB_OUTPUT
