name: docker-copy
description: Copy image between registries
  
inputs:
  source:
    description: Source image
    required: true
  tags:
    description: New tags
    required: true

runs:
  using: composite
  steps:
    -
      name: Set matrix
      id: set-matrix
      shell: bash
      run: |
        tags=""
        for tag in "${modified_dirs[@]}"; do
          tags="${tags} --tag ${tag}"
        done
        
        docker buildx imagetools create \
          $tags \
          ${{ inputs.source }}
