name: Build Dockerfiles

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      tag-suffix:
        required: true
        type: string
      push:
        required: false
        type: boolean
        default: false
    outputs:
      digest:
        description: "Image digest"
        value: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.docker-build-push.outputs.digest }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: |
#            name=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.AWS_REPOSITORY }}
#          tags: |
#            type=raw,suffix=_${{ inputs.tag-suffix }},value=${{ inputs.version }}
#            type=raw,suffix=_b${{ github.run_id }},value=${{ inputs.version }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      -
        name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
      -
        name: Build and load
        uses: docker/build-push-action@v5
        with:
          build-args: |
            AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}
            AWS_SECRET_ACCESS_KEY
            AWS_ACCESS_KEY_ID
            AWS_SESSION_TOKEN
          context: ./${{ inputs.version }}
          load: true
          tags: ${{ vars.AWS_REPOSITORY }}:${{ inputs.version }}
      -
        name: Test
        run: |
          docker run --rm --name rabbitmq-${{ inputs.version }} \
            --health-cmd='rabbitmq-diagnostics -q ping' \
            --health-interval=5s \
            --health-timeout=5s \
            --health-retries=10 \
            -d ${{ vars.AWS_REPOSITORY }}:${{ inputs.version }}
          docker ps
          docker stop rabbitmq-${{ inputs.version }}
      -
        name: Set platform
        run: |
          cd ./${{ inputs.version }}
          echo "PLATFORM=$(cat .platform)" >> "$GITHUB_ENV"     
      -
        name: Build and push
        id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}
            AWS_SECRET_ACCESS_KEY
            AWS_ACCESS_KEY_ID
            AWS_SESSION_TOKEN
          context: ./${{ inputs.version }}
          platforms: ${{ env.PLATFORM }}
          push: ${{ inputs.push }}
#          tags: ${{ steps.meta.outputs.tags }}
          tags: |
            ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.AWS_REPOSITORY }}:${{ inputs.version }}_${{ inputs.tag-suffix }}
            ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.AWS_REPOSITORY }}:${{ inputs.version }}_b${{ github.run_id }}
#          labels: ${{ steps.meta.outputs.labels }}
#      - 
#        id: get-build-name
#        run: |
#          imageName=${{ fromJSON(steps.docker-build-push.outputs.metadata)['image.name'] }}
#          echo "image_name=${imageName}" >> $GITHUB_OUTPUT
