name: Build Dockerfiles

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      push:
        required: false
        type: boolean
        default: false

jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Docker tags
        id: tags
        run: |
          environment="${{ inputs.environment }}"
          registry="${{ vars.DEV_AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.DEV_AWS_REGION }}.amazonaws.com/${{ vars.AWS_REPOSITORY }}"
          tags=()
          
          tags+=("${registry}:${{ inputs.version }}_b${{ github.run_id }}")
          
          case $environment in
            development) tags+=("${registry}:${{ inputs.version }}_dev") ;;
            test) tags+=("${registry}:${{ inputs.version }}_test") ;;
            production) tags+=("${registry}:${{ inputs.version }}_stable") ;;
            *) echo "Invalid environment!: ${environment}" && exit 1 ;;
          esac
  
          tags=$(jq -c -n '$ARGS.positional' --args "${tags[@]}")
          echo "tags=$tags" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.DEV_AWS_REGION }}
      -
        name: Login to dev ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DEV_AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.DEV_AWS_REGION }}.amazonaws.com
      -
        name: Build and load
        uses: docker/build-push-action@v5
        with:
          build-args: |
            AWS_ACCOUNT_ID=${{ vars.DEV_AWS_ACCOUNT_ID }}
            AWS_SECRET_ACCESS_KEY
            AWS_ACCESS_KEY_ID
            AWS_SESSION_TOKEN
          context: ./${{ inputs.version }}
          load: true
          tags: ${{ vars.AWS_REPOSITORY }}:${{ inputs.version }}
      -
        name: Test
        run: |
          docker run --rm --name rabbitmq-${{ inputs.version }} \
            --health-cmd='rabbitmq-diagnostics -q ping' \
            --health-interval=5s \
            --health-timeout=5s \
            --health-retries=10 \
            -d ${{ vars.AWS_REPOSITORY }}:${{ inputs.version }}
          docker ps
          docker stop rabbitmq-${{ inputs.version }}
      -
        name: Set platform
        run: |
          cd ./${{ inputs.version }}
          echo "PLATFORM=$(cat .platform)" >> "$GITHUB_ENV"     
      -
        name: Build and push
        id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            AWS_ACCOUNT_ID=${{ vars.DEV_AWS_ACCOUNT_ID }}
            AWS_SECRET_ACCESS_KEY
            AWS_ACCESS_KEY_ID
            AWS_SESSION_TOKEN
          context: ./${{ inputs.version }}
          platforms: ${{ env.PLATFORM }}
          push: ${{ inputs.push }}
          tags: ${{ steps.tags.outputs.tags }}
#          tags: |
#            ${{ vars.DEV_AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.DEV_AWS_REGION }}.amazonaws.com/${{ vars.AWS_REPOSITORY }}:${{ inputs.version }}_${{ inputs.tag-suffix }}
#            ${{ vars.DEV_AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.DEV_AWS_REGION }}.amazonaws.com/${{ vars.AWS_REPOSITORY }}:${{ inputs.version }}_b${{ github.run_id }}
