name: Build, test and push RabbitMQ images

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  list-versions:
    uses: ./.github/workflows/_list-versions.yml

  deploy-test:
    needs: list-versions
    if: ${{ needs.list-versions.outputs.versions != '[]' && needs.list-versions.outputs.versions != '' }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.versions) }}
    
    uses: ./.github/workflows/_build.yaml
    with:
      environment: Test
      version: ${{ matrix.version }}

  deploy-production:
    environment: Production
    needs:
      - list-versions
      - deploy-test
    if: ${{ needs.list-versions.outputs.versions != '[]' && needs.list-versions.outputs.versions != '' }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.versions) }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4