name: Build, test and push RabbitMQ images

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
    types: 
      - 'opened'
      - 'synchronize'

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID || '942465369820' }}
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  AWS_REPOSITORY: 'enterprise-rabbitmq'

jobs:
  list-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        id: set-matrix
        uses: ./.github/actions/list-versions

  verify:
    needs: list-versions
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.matrix) }}
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4 
      -
        name: Build and load
        #        uses: docker/build-push-action@v5
        run: |
          echo Build and load
          echo ${{ env.AWS_REPOSITORY }}:${{ matrix.version }}
      #        with:
      #          build-args: |
      #            AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }}
      #            AWS_SECRET_ACCESS_KEY
      #            AWS_ACCESS_KEY_ID
      #            AWS_SESSION_TOKEN
      #          context: ./${{ matrix.version }}
      #          load: true
      #          tags: ${{ env.AWS_REPOSITORY }}:${{ matrix.version }}
      -
        name: Test
        run: |
          echo Test docker image
          echo ${{ env.AWS_REPOSITORY }}:${{ matrix.version }}
      #          docker run --rm --name rabbitmq-${{ matrix.version }} \
      #            --health-cmd='rabbitmq-diagnostics -q ping' \
      #            --health-interval=5s \
      #            --health-timeout=5s \
      #            --health-retries=10 \
      #            -d ${{ env.AWS_REPOSITORY }}:${{ matrix.version }}
      #          docker ps
      #          docker stop rabbitmq-${{ matrix.version }}

  
  deploy-development:
    environment: Development
    if: github.event_name == 'pull_request'
    needs:
      - list-versions
      - verify
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.matrix) }}  
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      #      -
      #        name: Docker meta
      #        id: meta
      #        run: |
      #          echo "TAGS=${{ matrix.version }} >> "$GITHUB_ENV"
      #      -
      #        name: Set up QEMU
      #        uses: docker/setup-qemu-action@v3
      #      -
      #        name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v3
      #      -
      #        name: Configure AWS Credentials
      #        uses: aws-actions/configure-aws-credentials@v4
      #        with:
      #          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #          aws-region: ${{ env.AWS_REGION }} 

      #      -
      #        name: Set platform
      #        run: |
      #          cd ./${{ matrix.version }}
      #          echo "PLATFORM=$(cat .platform)" >> "$GITHUB_ENV"  
#      -
#        name: Set tags
#        run: |
#          cd ./${{ matrix.version }}
#          echo "TAGS=[${{ matrix.version }}_dev, ${{ matrix.version }}_b${{ github.run_number }}]" >> "$GITHUB_ENV" 
      -
        name: Build and push to dev
        run: |
          echo Build and push to development
          echo ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com${{ env.AWS_REPOSITORY }}:${{ matrix.version }}_pr${{ github.event.number }}

        
  deploy-test:
    environment: Test
    if: github.ref == 'refs/heads/master'
    needs:
      - list-versions
      - verify
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.matrix) }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      #      -
      #        name: Docker meta
      #        id: meta
      #        run: |
      #          echo "TAGS=${{ matrix.version }} >> "$GITHUB_ENV"
      #      -
      #        name: Set up QEMU
      #        uses: docker/setup-qemu-action@v3
      #      -
      #        name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v3
      #      -
      #        name: Configure AWS Credentials
      #        uses: aws-actions/configure-aws-credentials@v4
      #        with:
      #          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #          aws-region: ${{ env.AWS_REGION }}
      #      -
      #        name: Login to ECR
      #        uses: docker/login-action@v3
      #        with:
      #          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
   
      -
        name: Build and push to test
        run: |
          echo Build and push to development
          echo ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_REPOSITORY }}:${{ matrix.version }}_test
          echo ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com${{ env.AWS_REPOSITORY }}:${{ matrix.version }}_b${{ github.run_number }}

  deploy-production:
    environment: Production
    if: github.ref == 'refs/heads/master'
    needs:
      - list-versions
      - deploy-test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.matrix) }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and push to production
        #        uses: docker/build-push-action@v5
        run: |
          echo Build and push to production
          echo ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_REPOSITORY }}:${{ matrix.version }}_stable         
#        with:
#          build-args: |
#            AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }}
#            AWS_SECRET_ACCESS_KEY
#            AWS_ACCESS_KEY_ID
#            AWS_SESSION_TOKEN
#          context: ./${{ matrix.version }}
#          platforms: ${{ env.PLATFORM }}
#          push: true
#          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_REPOSITORY }}:${{ matrix.version }}
