name: Build, test and push RabbitMQ images

on:
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  list-versions:
    uses: ./.github/workflows/_list-versions.yml

  deploy-development:
    needs: list-versions
    if: ${{ needs.list-versions.outputs.versions != '[]' && needs.list-versions.outputs.versions != '' }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.versions) }}
    
    uses: ./.github/workflows/_build.yml
    with:
      environment: Development
      version: ${{ matrix.version }}
      tag-suffix: "dev"
      push: true
