name: Build, test and push RabbitMQ images

on:
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

#env:
#  AWS_REPOSITORY: 'enterprise-rabbitmq'

jobs:
  list-versions:
    uses: ./.github/workflows/_list-versions.yaml

  test:
    needs: list-versions
    if: ${{ needs.list-versions.outputs.versions != '[]' && needs.list-versions.outputs.versions != '' }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.versions) }}
    
    uses: ./.github/workflows/_test.yaml
    with:
      version: ${{ matrix.version }}
      role-to-assume: ${{ vars.AWS_ROLE }}
      region: ${{ vars.AWS_REGION }}
      account-id: ${{ vars.AWS_ACCOUNT_ID }}
      repository: ${{ vars.AWS_REPOSITORY }}
